# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  pinguim_config = debug

else ifeq ($(config),release)
  pinguim_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := pinguim

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

pinguim:
ifneq (,$(pinguim_config))
	@echo "==== Building pinguim ($(pinguim_config)) ===="
	@${MAKE} --no-print-directory -C pinguim -f Makefile config=$(pinguim_config)
endif

clean:
	@${MAKE} --no-print-directory -C pinguim -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   pinguim"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"